
# set port 8080 for the application
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5333/books_users}
spring.datasource.username=${DB_USERNAME:books}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Show all logs for debugging purposes
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.example.booksusers=DEBUG

# Show SQL statements in the logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true